services:
  frontend:
    build:
      context: ./dobbelen-frontend
      dockerfile: Dockerfile
    ports:
      - "48081:80"
    networks:
      - app-network

  backend:
    build:
      context: ./dobbelen-backend
      dockerfile: Dockerfile
    ports:
      - "48080:48080"
      - "5014:5005"  # Map host port 5014 to container port 5005
    networks:
      - app-network

networks:
  app-network:
    driver: bridge