import React, { useState, useEffect, useCallback } from 'react';
import { Game } from '../types/game';
import { gameApi } from '../api/gameApi';
import { useLanguage } from '../contexts/LanguageContext';
import { aiService } from '../services/aiService';
import { audioService } from '../services/audioService';
import { sanitizeUsername, MAX_USERNAME_LENGTH } from '../utils/username';

interface MultiplayerLobbyProps {
  onGameStart: (game: Game, playerId: string, username: string) => void;
  onBack: () => void;
}

// Dutch names for random selection
const DUTCH_NAMES = [
  'Henk', 'Jan', 'Piet', 'Klaas', 'Willem', 'Dirk', 'Frits', 'Gerard', 'Hendrik', 'Kees',
  'Maarten', 'Niels', 'Otto', 'Paul', 'Rik', 'Sander', 'Tom', 'Vincent', 'Wouter', 'Yuri',
  'Anna', 'Bianca', 'Carla', 'Diana', 'Eva', 'Fleur', 'Gina', 'Hanna', 'Iris', 'Julia',
  'Kim', 'Lisa', 'Marijke', 'Nina', 'Olga', 'Petra', 'Rosa', 'Sanne', 'Tessa', 'Ursula'
];

const MultiplayerLobby: React.FC<MultiplayerLobbyProps> = ({ onGameStart, onBack }) => {
  const { t } = useLanguage();
  const [gameId, setGameId] = useState("");
  const [playerName, setPlayerName] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const [isJoining, setIsJoining] = useState(false);
  const [error, setError] = useState("");
  const [game, setGame] = useState<Game | null>(null);
  const [isHost, setIsHost] = useState(false);
  const [hasJoined, setHasJoined] = useState(false);
  const [isInitialized, setIsInitialized] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [isPrivateGame, setIsPrivateGame] = useState(false);
  const [lobbyGames, setLobbyGames] = useState<Game[]>([]);
  const [lobbyExpanded, setLobbyExpanded] = useState(false);
  const [myPlayerId, setMyPlayerId] = useState<string | null>(null);
  const [countdownSeconds, setCountdownSeconds] = useState<number | null>(null);

  // Single place: return to main lobby and allow rejoin (kicked, 404, or user clicked Back)
  const resetToMainLobby = useCallback((gameIdToClear?: string) => {
    if (gameIdToClear) {
      sessionStorage.removeItem(`lobby_${gameIdToClear}`);
      sessionStorage.removeItem("game_session");
      window.history.replaceState({}, "", `${window.location.origin}${window.location.pathname}`);
    }
    setGame(null);
    setGameId("");
    setIsHost(false);
    setHasJoined(false);
    setError("");
    setIsJoining(false);
    setMyPlayerId(null);
  }, []);

  // Update audio service when mute state changes
  useEffect(() => {
    audioService.setMuted(isMuted);
  }, [isMuted]);

  // Short game IDs are now generated by the backend

  // Get a random Dutch name
  const getRandomDutchName = () => {
    return DUTCH_NAMES[Math.floor(Math.random() * DUTCH_NAMES.length)];
  };

  // Separate function to join game with a specific ID
  const handleAutoJoin = useCallback(
    async (
      gameIdToJoin: string,
      options?: { updateHistory?: boolean; playerNameOverride?: string }
    ) => {
      // Allow passing an override player name to avoid race conditions
      const nameToUse = options?.playerNameOverride ?? playerName;

      if (!nameToUse?.trim() || hasJoined) {
        return;
      }

      try {
        setIsJoining(true);
        setError("");

        console.log(
          "Auto-joining game with ID:",
          gameIdToJoin,
          "and name:",
          nameToUse
        );
        const joinedGame = await gameApi.joinMultiplayerGame(
          gameIdToJoin,
          nameToUse
        );
        console.log("Auto-joined game successfully:", joinedGame);

        const me = joinedGame.players.find((p) => p.name === nameToUse);
        setGameId(gameIdToJoin);
        setGame(joinedGame);
        setIsHost(false);
        setHasJoined(true);
        setMyPlayerId(me?.id ?? null);

        // Optionally update URL with game ID
        if (options?.updateHistory !== false) {
          const newUrl = `${window.location.origin}${window.location.pathname}?gameId=${gameIdToJoin}`;
          window.history.pushState({}, "", newUrl);
        }
      } catch (err: any) {
        console.error("Error auto-joining game:", err);
        // If join failed, try fetching the game to determine if it exists.
        try {
          await gameApi.getMultiplayerGame(gameIdToJoin);
          // If the GET succeeded the game exists; show the server-provided message if present
          setError(
            err.response?.data?.message ||
              err.message ||
              t("lobby.failedToJoinGame")
          );
        } catch (getErr) {
          // If GET failed, the game likely doesn't exist
          setError("game not found");
        }
      } finally {
        setIsJoining(false);
      }
    },
    [playerName, hasJoined, t]
  );

  const LOBBY_STORAGE_KEY = (id: string) => `lobby_${id}`;

  // Initialize component - only run once
  useEffect(() => {
    if (isInitialized) return;

    const urlParams = new URLSearchParams(window.location.search);
    const urlGameId = urlParams.get("gameId");
    if (urlGameId) {
      const saved = sessionStorage.getItem(LOBBY_STORAGE_KEY(urlGameId));
      if (saved) {
        try {
          const { playerName: savedName, isHost: savedHost } = JSON.parse(saved);
          if (!savedName) {
            sessionStorage.removeItem(LOBBY_STORAGE_KEY(urlGameId));
            setGameId(urlGameId);
          } else {
            setGameId(urlGameId);
            gameApi.getMultiplayerGame(urlGameId).then((fetched) => {
              const me = fetched.players.find((p) => p.name === savedName);
              setGame(fetched);
              setPlayerName(savedName);
              setIsHost(!!savedHost);
              setHasJoined(true);
              setMyPlayerId(me?.id ?? null);
            }).catch(() => {
              sessionStorage.removeItem(LOBBY_STORAGE_KEY(urlGameId));
              window.history.replaceState({}, "", `${window.location.origin}${window.location.pathname}`);
            });
          }
        } catch {
          setGameId(urlGameId);
          window.history.replaceState({}, "", `${window.location.origin}${window.location.pathname}`);
        }
      } else {
        setGameId(urlGameId);
        window.history.replaceState({}, "", `${window.location.origin}${window.location.pathname}`);
      }
    }

    setIsInitialized(true);
  }, [isInitialized]);

  // Countdown ticker when game is in COUNTDOWN state (visible to all players)
  useEffect(() => {
    if (game?.state !== "COUNTDOWN" || game?.countdownEndTime == null) {
      setCountdownSeconds(null);
      return;
    }
    const endMs = typeof game.countdownEndTime === "number" ? game.countdownEndTime : null;
    if (endMs == null) return;
    const tick = () => {
      const remaining = Math.ceil((endMs - Date.now()) / 1000);
      setCountdownSeconds(remaining > 0 ? remaining : 0);
    };
    tick();
    const interval = setInterval(tick, 200);
    return () => clearInterval(interval);
  }, [game?.state, game?.countdownEndTime]);

  // Fetch lobby list when on main screen (no game joined)
  useEffect(() => {
    if (game || !isInitialized) return;
    const loadLobby = async () => {
      try {
        const list = await gameApi.listMultiplayerGames();
        setLobbyGames(list);
      } catch {
        setLobbyGames([]);
      }
    };
    loadLobby();
    const interval = setInterval(loadLobby, 5000);
    return () => clearInterval(interval);
  }, [game, isInitialized]);

  // Poll for game updates when in a game - only fetch, don't join
  useEffect(() => {
    if (!game || !gameId || !isInitialized) return;

    const pollInterval = setInterval(async () => {
      try {
        console.log("Polling game updates for gameId:", gameId);
        const updatedGame = await gameApi.getMultiplayerGame(gameId);
        console.log(
          "Polled game state:",
          updatedGame.state,
          "players:",
          updatedGame.players.length
        );

        // Register AI players when game is updated
        updatedGame.players.forEach((player) => {
          if (
            player.name.startsWith("AI ") ||
            player.name.startsWith("🧠AI ")
          ) {
            aiService.registerAIPlayer(player.id, player.name);
            console.log("Registered AI player:", player.name, player.id);
          }
        });

        // Kicked or no longer in game: return to main lobby (by id if we have it, else by name)
        const stillInGame = myPlayerId
          ? updatedGame.players.some((p) => p.id === myPlayerId)
          : updatedGame.players.some((p) => p.name === playerName);
        if (!stillInGame) {
          resetToMainLobby(gameId);
          return;
        }

        // Check if game has started (from waiting or from countdown)
        if (
          updatedGame.state === "IN_PROGRESS" &&
          (game.state === "WAITING_FOR_PLAYERS" || game.state === "COUNTDOWN")
        ) {
          console.log("Game started! Transitioning to game table...");
          const player = myPlayerId
            ? updatedGame.players.find((p) => p.id === myPlayerId)
            : updatedGame.players.find((p) => p.name === playerName);
          if (player) {
            onGameStart(updatedGame, player.id, player.name);
          }
        }

        setGame(updatedGame);
      } catch (err: any) {
        console.error("Error polling game updates:", err);
        if (err.response?.status === 404) {
          resetToMainLobby(gameId);
        }
      }
    }, 1000); // Poll every 1 second so new joiners and kick are reflected quickly

    return () => clearInterval(pollInterval);
  }, [game, gameId, isInitialized, playerName, myPlayerId, onGameStart, resetToMainLobby]);

  const createGame = async () => {
    if (!playerName.trim()) {
      setError(t("lobby.pleaseEnterUsername"));
      return;
    }

    try {
      setIsCreating(true);
      setError("");

      console.log("Creating multiplayer game...");
      const gameResponse = await gameApi.createMultiplayerGame(isPrivateGame);
      console.log("Game created successfully:", gameResponse);

      // Add the host (creator) to the game
      const updatedGame = await gameApi.joinMultiplayerGame(
        gameResponse.id,
        playerName
      );
      console.log("Host joined game successfully:", updatedGame);

      const me = updatedGame.players.find((p) => p.name === playerName);
      setGame(updatedGame);
      setGameId(updatedGame.id);
      setIsHost(true);
      setHasJoined(true);
      setMyPlayerId(me?.id ?? null);
      sessionStorage.setItem(`lobby_${updatedGame.id}`, JSON.stringify({ playerName, isHost: true }));

      // Update URL with game ID (keep in URL so refresh restores lobby)
      const newUrl = `${window.location.origin}${window.location.pathname}?gameId=${updatedGame.id}`;
      window.history.pushState({}, "", newUrl);
    } catch (err: any) {
      console.error("Error creating game:", err);
      setError(
        err.response?.data?.message ||
          err.message ||
          t("lobby.failedToCreateGame")
      );
    } finally {
      setIsCreating(false);
    }
  };

  const joinGame = async () => {
    if (!gameId.trim() || !playerName.trim()) {
      setError(
        t("lobby.pleaseEnterGameId") + " " + t("lobby.pleaseEnterUsername")
      );
      return;
    }

    // Prevent duplicate joins
    if (hasJoined) {
      console.log("Already joined a game, skipping duplicate join attempt");
      return;
    }

    try {
      setIsJoining(true);
      setError("");

      console.log("Joining game with ID:", gameId, "and name:", playerName);
      const joinedGame = await gameApi.joinMultiplayerGame(gameId, playerName);
      console.log("Joined game successfully:", joinedGame);

      const me = joinedGame.players.find((p) => p.name === playerName);
      setGame(joinedGame);
      setIsHost(false);
      setHasJoined(true);
      setMyPlayerId(me?.id ?? null);
      sessionStorage.setItem(`lobby_${gameId}`, JSON.stringify({ playerName, isHost: false }));

      // Update URL with game ID (keep in URL so refresh restores lobby)
      const newUrl = `${window.location.origin}${window.location.pathname}?gameId=${gameId}`;
      window.history.pushState({}, "", newUrl);
    } catch (err: any) {
      console.error("Error joining game:", err);
      console.error("Error details:", err.response?.data);
      // Probe the game endpoint to decide whether the game code is missing
      try {
        await gameApi.getMultiplayerGame(gameId);
        setError(
          err.response?.data?.message ||
            err.message ||
            t("lobby.failedToJoinGame")
        );
      } catch (getErr) {
        setError("Game not found");
      }
    } finally {
      setIsJoining(false);
    }
  };

  const addAIPlayer = async (difficulty: "easy" | "medium" = "easy") => {
    if (!game || !isHost) return;

    try {
      // Get all existing AI player names to avoid duplicates
      const existingAINames = game.players
        .filter((p) => p.name.startsWith("AI ") || p.name.startsWith("🧠AI "))
        .map((p) => p.name.replace(/^(AI |🧠AI )/, ""));

      let aiName;
      let baseName;
      do {
        baseName = getRandomDutchName();
      } while (existingAINames.includes(baseName));

      const prefix = difficulty === "medium" ? "🧠AI " : "AI ";
      aiName = `${prefix}${baseName}`;

      const updatedGame = await gameApi.joinMultiplayerGame(game.id, aiName);
      setGame(updatedGame);
      console.log("Added AI player:", aiName, "(difficulty:", difficulty, ")");
    } catch (err: any) {
      console.error("Error adding AI player:", err);
      setError(t("errors.failedToAddPlayer"));
    }
  };

  const removeAIPlayer = async (playerId: string) => {
    if (!game || !isHost) return;

    try {
      const player = game.players.find((p) => p.id === playerId);
      const isAI =
        player &&
        (player.name.startsWith("AI ") || player.name.startsWith("🧠AI "));
      if (!player || !isAI) {
        console.warn("Cannot remove non-AI player");
        return;
      }

      const updatedGame = await gameApi.removePlayer(gameId, playerId);
      setGame(updatedGame);
      console.log("Removed AI player:", player.name);
    } catch (err: any) {
      console.error("Error removing AI player:", err);
      setError(t("errors.failedToRemove") || "Failed to remove AI player");
    }
  };

  const kickPlayer = async (playerId: string) => {
    if (!game || !isHost) return;
    const hostId = game.players[0]?.id;
    if (playerId === hostId) return; // Host uses "Cancel game" to leave

    try {
      const updatedGame = await gameApi.removePlayer(gameId, playerId);
      setGame(updatedGame);
    } catch (err: any) {
      console.error("Error kicking player:", err);
      setError(err.response?.data?.message || err.message || "Failed to remove player");
    }
  };

  const copyGameLink = () => {
    const gameLink = `${window.location.origin}${window.location.pathname}?gameId=${gameId}`;
    navigator.clipboard.writeText(gameLink);
  };

  const handleCancelNewGame = () => {
    resetToMainLobby(gameId || undefined);
  };

  return (
    <div className="flex flex-col min-h-screen bg-green-800 select-none">
      {/* Invisible top bar: volume + language sit here (language is in App.tsx) */}
      <div className="flex-shrink-0 h-14 flex items-center justify-between px-4 bg-green-800">
        <button
          onClick={() => setIsMuted(!isMuted)}
          className="bg-black bg-opacity-50 text-white px-3 py-2 rounded-lg hover:bg-opacity-70 font-medium shadow-lg text-sm transition-all duration-200"
          aria-label={isMuted ? "Unmute" : "Mute"}
        >
          {isMuted ? "🔇" : "🔊"}
        </button>
        <div className="w-10" />
      </div>

      <div className="flex-1 flex items-start md:items-center justify-center p-4 pt-2 md:pt-4 overflow-auto">
        <div className="bg-white p-4 md:p-8 rounded-3xl shadow-lg max-w-sm md:max-w-lg w-full border-4 border-black">
        {!game ? (
          <div className="space-y-4 md:space-y-6">
            <h1 className="text-2xl md:text-4xl font-bold text-center text-green-800">
              {t("game.title")}
            </h1>
            {/* Player Name */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                {t("lobby.username")}
              </label>
              <div className="flex space-x-2">
                <input
                  type="text"
                  value={playerName}
                  onChange={(e) => setPlayerName(sanitizeUsername(e.target.value))}
                  onFocus={(e) => e.target.select()}
                  className="flex-1 min-w-0 p-2 md:p-3 border rounded-lg focus:ring-2 focus:ring-green-500 text-base md:text-lg"
                  placeholder={t("lobby.enterUsername")}
                  maxLength={MAX_USERNAME_LENGTH}
                  autoFocus
                />
                <button
                  onClick={() => {
                    audioService.playRaise();
                    setPlayerName(getRandomDutchName());
                  }}
                  className="w-10 h-10 md:w-12 md:h-12 flex-shrink-0 p-0 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 font-medium flex items-center justify-center"
                  aria-label="Randomize name"
                >
                  <img
                    src="/dobbelen.svg"
                    alt="Dobbelen Logo"
                    className="w-full h-full object-contain"
                  />
                </button>
              </div>
            </div>

            {/* Private game checkbox + New Game */}
            <div className="space-y-3">
              <label className="flex items-center justify-center gap-1.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isPrivateGame}
                  onChange={(e) => setIsPrivateGame(e.target.checked)}
                  className="w-3 h-3 rounded border-gray-300 text-green-600 focus:ring-green-500"
                />
                <span className="text-xs text-gray-600">{t("lobby.privateGame")}</span>
              </label>
              <button
                onClick={() => {
                  audioService.playRaise();
                  createGame();
                }}
                disabled={isCreating || !playerName.trim()}
                className="w-full py-3 md:py-4 px-4 md:px-6 bg-green-600 text-white rounded-2xl hover:bg-green-700 disabled:opacity-50 text-lg md:text-xl font-bold"
              >
                {isCreating ? t("lobby.creating") : t("lobby.createGame")}
              </button>
            </div>

            <div className="flex items-center space-x-2 md:space-x-4">
              <div className="flex-1 h-px bg-gray-300"></div>
              <span className="text-gray-500 font-medium text-sm md:text-base">
                {t("lobby.or")}
              </span>
              <div className="flex-1 h-px bg-gray-300"></div>
            </div>

            <div className="min-w-0">
              <div className="flex gap-2 min-w-0">
                <input
                  type="text"
                  value={gameId}
                  onChange={(e) => setGameId(e.target.value.toLowerCase())}
                  onFocus={(e) => e.target.select()}
                  onKeyPress={(e) => {
                    if (
                      e.key === "Enter" &&
                      gameId.trim() &&
                      playerName.trim() &&
                      !isJoining
                    ) {
                      joinGame();
                    }
                  }}
                  className="flex-1 min-w-0 w-0 p-2 md:p-3 border rounded-lg focus:ring-2 focus:ring-blue-500 text-base md:text-lg font-mono text-center"
                  placeholder={t("lobby.gameId")}
                  maxLength={3}
                />
                <button
                  onClick={() => {
                    audioService.playRaise();
                    joinGame();
                  }}
                  disabled={isJoining || !gameId.trim() || !playerName.trim()}
                  className="flex-shrink-0 px-3 md:px-6 py-2 md:py-3 bg-blue-600 text-white rounded-2xl hover:bg-blue-700 disabled:opacity-50 font-bold text-sm md:text-base whitespace-nowrap"
                >
                  {isJoining ? t("lobby.joining") : t("lobby.joinGame")}
                </button>
              </div>
            </div>

            {/* Game lobby - at bottom, show 3 by default; if more than 3, "Show more" expands to 8 with scroll */}
            {lobbyGames.length > 0 && (
              <div>
                <h3 className="text-sm font-medium text-gray-700 mb-2">{t("lobby.gameLobby")}</h3>
                {(() => {
                  const visible = lobbyExpanded ? lobbyGames : lobbyGames.slice(0, 3);
                  const hasMore = lobbyGames.length > 3;
                  return (
                    <>
                      <ul
                        className={`space-y-1 rounded-lg border border-gray-200 bg-gray-50 p-2 ${
                          lobbyExpanded ? "max-h-72 overflow-y-auto" : ""
                        }`}
                      >
                        {visible.map((g) => (
                          <li key={g.id}>
                            <button
                              type="button"
                              onClick={() => {
                                audioService.playRaise();
                                handleAutoJoin(g.id);
                              }}
                              className="w-full text-left px-3 py-1.5 rounded hover:bg-gray-200 flex flex-col gap-0.5"
                            >
                              <span className="flex items-center justify-between">
                                <span className="font-mono font-bold text-green-700">{g.id}</span>
                                <span className="text-xs text-gray-500">{g.players?.length ?? 0}/6</span>
                              </span>
                              {(g.players?.length ?? 0) > 0 && (
                                <span className="text-[10px] text-gray-400 truncate" title={g.players?.map((p) => p.name).join(", ")}>
                                  {g.players?.map((p) => p.name).join(", ")}
                                </span>
                              )}
                            </button>
                          </li>
                        ))}
                      </ul>
                      {hasMore && (
                        <button
                          type="button"
                          onClick={() => {
                            audioService.playRaise();
                            setLobbyExpanded((e) => !e);
                          }}
                          className="mt-1.5 text-xs text-green-600 hover:text-green-700 font-medium"
                        >
                          {lobbyExpanded ? t("lobby.showLess") : t("lobby.showMore")}
                        </button>
                      )}
                    </>
                  );
                })()}
              </div>
            )}
          </div>
        ) : (
          <div className="space-y-4 md:space-y-6 relative">
            {game?.state === "COUNTDOWN" && (
              <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70">
                <div className="text-white text-center">
                  <p className="text-xl md:text-2xl font-medium mb-4">{t("lobby.gameStarting")}</p>
                  <p className="text-7xl md:text-9xl font-bold tabular-nums">
                    {countdownSeconds !== null && countdownSeconds > 0 ? countdownSeconds : t("lobby.go")}
                  </p>
                </div>
              </div>
            )}
            <div className="text-center">
              {!isHost && (
                <p className="text-sm md:text-base text-gray-600 mb-3">
                  {t("lobby.waitingForHostToStart")}
                </p>
              )}
              {!isHost && (
                <button
                  type="button"
                  onClick={async () => {
                    audioService.playRaise();
                    const me = myPlayerId
                      ? game.players.find((p) => p.id === myPlayerId)
                      : game.players.find((p) => p.name === playerName);
                    if (me) {
                      try {
                        await gameApi.removePlayer(gameId, me.id);
                      } catch {
                        // Still leave the lobby locally if API fails (e.g. game already gone)
                      }
                    }
                    handleCancelNewGame();
                  }}
                  className="mb-3 w-full py-2 px-4 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 font-medium text-sm"
                >
                  ← {t("lobby.back")}
                </button>
              )}
              <div className="bg-gray-100 p-3 md:p-4 rounded-lg min-w-0 overflow-hidden">
                <p className="text-xs md:text-sm text-gray-600 mb-1">
                  {t("lobby.gameId")}
                </p>
                <p className="text-lg md:text-2xl font-mono font-bold text-green-600 truncate">
                  {game?.id ?? gameId}
                </p>
                <p className="text-sm text-gray-600 mt-1">
                  {t("lobby.youAre")}: <span className="font-semibold text-gray-800">{playerName}</span>
                </p>
              </div>
            </div>

            <div className="bg-gray-100 p-3 md:p-4 rounded-lg">
              <h3 className="font-bold mb-2 md:mb-3 text-base md:text-lg">
                {t("lobby.players")} ({game.players.length})
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {game.players.map((player, index) => {
                  console.log("MultiplayerLobby player color:", player.color);
                  const colorClassMap: Record<string, string> = {
                    blue: "bg-indigo-600",
                    red: "bg-rose-600",
                    green: "bg-emerald-600",
                    yellow: "bg-amber-600",
                    brown: "bg-amber-700", // rich cognac brown
                    cyan: "bg-cyan-600",
                    purple: "bg-purple-600",
                    pink: "bg-pink-600",
                  };
                  let playerColorClass = colorClassMap[player.color];
                  if (!playerColorClass) {
                    console.warn("Unknown player color:", player.color);
                    playerColorClass = "bg-rose-700"; // fallback to rose for visibility
                  }
                  return (
                    <div
                      key={player.id}
                      className="flex items-center bg-white p-2 rounded"
                    >
                      <span
                        className={`w-5 h-5 md:w-6 md:h-6 ${playerColorClass} text-white rounded-full flex items-center justify-center text-xs md:text-sm mr-2 font-bold`}
                      >
                        {index + 1}
                      </span>
                      <span className="font-medium text-sm md:text-base flex-1">
                        {player.name.startsWith("🧠AI ") ? (
                          <span>
                            {player.name.replace(/^🧠AI /, "")}
                            <span className="ml-1 text-xs bg-purple-600 text-white px-1.5 py-0.5 rounded">
                              🧠 Medium
                            </span>
                          </span>
                        ) : player.name.startsWith("AI ") ? (
                          <span>
                            {player.name.replace("AI ", "")}
                            <span className="ml-1 text-xs bg-green-600 text-white px-1.5 py-0.5 rounded">
                              🎲 Easy
                            </span>
                          </span>
                        ) : (
                          <>
                            {player.name}
                            {index === 0 && <span className="ml-1" title={t("lobby.host")}>👑</span>}
                          </>
                        )}
                      </span>
                      {isHost && game.players[0]?.id !== player.id && (
                        <button
                          onClick={() => {
                            audioService.playRaise();
                            if (
                              player.name.startsWith("AI ") ||
                              player.name.startsWith("🧠AI ")
                            ) {
                              removeAIPlayer(player.id);
                            } else {
                              kickPlayer(player.id);
                            }
                          }}
                          className="ml-2 w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center text-xs hover:bg-red-600"
                          title={player.name.startsWith("AI ") || player.name.startsWith("🧠AI ") ? "Remove AI player" : "Kick player"}
                        >
                          ×
                        </button>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {isHost && (
              <div className="space-y-2 md:space-y-3">
                <button
                  onClick={() => {
                    audioService.playRaise();
                    copyGameLink();
                  }}
                  className="w-full py-2 md:py-3 px-3 md:px-4 bg-yellow-500 text-white rounded-lg hover:bg-yellow-600 font-bold text-sm md:text-base"
                >
                  📋 {t("lobby.clickToCopyLink")}
                </button>
                <div className="flex gap-2 flex-wrap">
                  <button
                    onClick={() => {
                      audioService.playRaise();
                      addAIPlayer("easy");
                    }}
                    className="flex-1 min-w-0 py-2 md:py-3 px-2 md:px-3 bg-green-600 text-white rounded-lg hover:bg-green-700 font-bold text-xs md:text-sm whitespace-nowrap"
                    disabled={game.players.length >= 6}
                  >
                    🎲 Easy AI
                  </button>
                  <button
                    onClick={() => {
                      audioService.playRaise();
                      addAIPlayer("medium");
                    }}
                    className="flex-1 min-w-0 py-2 md:py-3 px-2 md:px-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 font-bold text-xs md:text-sm whitespace-nowrap"
                    disabled={game.players.length >= 6}
                  >
                    🧠 Medium AI
                  </button>
                </div>
                <p className="text-xs text-center text-gray-600">
                  ({game.players.length}/6 players)
                </p>
                <button
                  onClick={async () => {
                    audioService.playRaise();
                    try {
                      console.log("Starting multiplayer game (3s countdown)...");
                      const startedGame = await gameApi.startMultiplayerGame(gameId);
                      setGame(startedGame);
                      setError("");
                    } catch (err: any) {
                      console.error("Error starting game:", err);
                      setError(
                        err.response?.data?.message ||
                          err.message ||
                          t("errors.failedToStart")
                      );
                    }
                  }}
                  className="w-full py-3 md:py-4 px-4 md:px-6 bg-green-600 text-white rounded-lg hover:bg-green-700 font-bold text-lg md:text-xl disabled:opacity-50"
                  disabled={game.players.length < 2}
                >
                  🚀 {t("lobby.startGame")}
                </button>
                {game.players.length < 2 && (
                  <p className="mt-1 text-xs text-center text-red-600">
                    {t("lobby.needAtLeastTwoPlayers") || "At least 2 players required to start"}
                  </p>
                )}
              </div>
            )}

            {isHost && (
              <button
                type="button"
                onClick={async () => {
                  audioService.playRaise();
                  const hostPlayer = game.players.find((p) => p.name === playerName);
                  if (hostPlayer) {
                    try {
                      await gameApi.cancelMultiplayerGame(gameId, hostPlayer.id);
                      handleCancelNewGame();
                    } catch (err: any) {
                      setError(err.response?.data?.message || err.message || t("lobby.failedToCreateGame"));
                    }
                  }
                }}
                className="w-full py-2 px-4 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 font-medium text-sm"
              >
                {t("lobby.cancelGame")}
              </button>
            )}
          </div>
        )}

        {error && (
          <div className="mt-3 md:mt-4 p-3 md:p-4 bg-red-100 border border-red-400 text-red-700 rounded-lg text-sm md:text-base">
            ❌ {error}
          </div>
        )}
        </div>
      </div>
    </div>
  );
};

export default MultiplayerLobby;
